### ISSUE TITLE
Glob.glob() infuriatingly slow in crawler script

### ISSUE THREAD

**Issue by brenshanny** [htem/utilities#2]
Find alternative to glob.glob for crawler script. Maybe os.listdir()?

**Comment by davidhildebrand** [comment]
Relevant: https://stackoverflow.com/questions/13643558/shoud-glob-glob-be-preferred-over-os-listdir-or-the-other-way-around

**Comment by brenshanny** [comment]
Thanks! Guess they're the same in the end since glob.glob uses os.listdir()
